# Generated by Django 5.2.15 on 2026-07-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingesta', 'Ingesta bulk'), ('evaluacion', 'Evaluación de filtros'), ('enriquecimiento', 'Enriquecimiento API'), ('sincronizacion', 'Sincronización de estados'), ('importacion_pivot', 'Importación de PIVOT')], max_length=20)),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('exitosa', 'Exitosa'), ('fallida', 'Fallida')], default='en_curso', max_length=10)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('terminada_en', models.DateTimeField(blank=True, null=True)),
                ('metricas', models.JSONField(blank=True, default=dict)),
                ('log_resumen', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'ejecución de pipeline',
                'verbose_name_plural': 'ejecuciones de pipeline',
                'ordering': ['-iniciada_en'],
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('moneda', models.CharField(choices=[('UTM', 'Unidad Tributaria Mensual'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], max_length=3)),
                ('tasa_clp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tipo de cambio',
                'verbose_name_plural': 'tipos de cambio',
                'ordering': ['-fecha', 'moneda'],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'moneda'), name='tasa_unica_por_dia')],
            },
        ),
    ]
