# Generated by Django 5.2.15 on 2026-07-05 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitaciones', '0001_initial'),
        ('perfiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('en_revision', 'En revisión'), ('preparando_oferta', 'Preparando oferta'), ('presentada', 'Oferta presentada'), ('descartada', 'Descartada')], default='nueva', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='licitaciones.licitacion')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='perfiles.perfilfiltro')),
            ],
            options={
                'verbose_name': 'gestión de licitación',
                'verbose_name_plural': 'gestiones de licitación',
                'indexes': [models.Index(fields=['perfil', 'estado'], name='gestion_ges_perfil__e18f9e_idx')],
                'constraints': [models.UniqueConstraint(fields=('licitacion', 'perfil'), name='una_gestion_por_equipo')],
            },
        ),
    ]
