# Generated by Django 5.2.15 on 2026-07-05 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('ops', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('generico', models.TextField(blank=True, default='')),
                ('descripcion_producto', models.TextField(blank=True, default='')),
                ('tipo_adquisicion', models.CharField(blank=True, default='', max_length=120)),
                ('estado_fuente', models.CharField(blank=True, default='', max_length=60)),
                ('monto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('moneda', models.CharField(blank=True, choices=[('CLP', 'Peso chileno'), ('UTM', 'Unidad Tributaria Mensual'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='', max_length=3)),
                ('monto_clp_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('url_ficha', models.URLField(blank=True, default='', max_length=300)),
                ('raw_bulk', models.JSONField(blank=True, default=dict)),
                ('raw_api', models.JSONField(blank=True, null=True)),
                ('enriquecida_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitaciones_nuevas', to='ops.ejecucionpipeline')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licitaciones', to='catalogo.organismo')),
                ('rubros', models.ManyToManyField(blank=True, related_name='licitaciones', to='catalogo.rubro')),
            ],
            options={
                'verbose_name': 'licitación',
                'verbose_name_plural': 'licitaciones',
                'ordering': ['-fecha_publicacion', 'codigo_externo'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('incluida', 'Incluida'), ('bypass', 'Incluida por bypass'), ('sin_match', 'Sin match de inclusión'), ('excluida', 'Excluida'), ('exclusion_dura', 'Exclusión dura'), ('vetada', 'Vetada por intención')], max_length=20)),
                ('confianza', models.CharField(choices=[('alta', 'Alta (servicio profesional)'), ('revisar', 'Revisar (zona gris)'), ('na', 'No aplica')], default='na', max_length=10)),
                ('trazabilidad', models.JSONField(blank=True, default=dict)),
                ('evaluada_en', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='perfiles.perfilfiltro')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='licitaciones.licitacion')),
            ],
            options={
                'verbose_name': 'evaluación de filtro',
                'verbose_name_plural': 'evaluaciones de filtro',
            },
        ),
        migrations.AddIndex(
            model_name='licitacion',
            index=models.Index(fields=['fecha_cierre'], name='licitacione_fecha_c_34f82a_idx'),
        ),
        migrations.AddIndex(
            model_name='licitacion',
            index=models.Index(fields=['estado_fuente'], name='licitacione_estado__4c58e6_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionfiltro',
            index=models.Index(fields=['perfil', 'resultado'], name='licitacione_perfil__78c557_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluacionfiltro',
            constraint=models.UniqueConstraint(fields=('licitacion', 'perfil'), name='una_evaluacion_por_perfil'),
        ),
    ]
