# Generated by Django 5.2.15 on 2026-07-06 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionfiltro',
            name='evaluada_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
