# Generated by Django 5.2.15 on 2026-07-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, unique=True)),
                ('codigo', models.CharField(blank=True, default='', max_length=50)),
                ('region', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name': 'organismo',
                'verbose_name_plural': 'organismos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3')])),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'rubro',
                'verbose_name_plural': 'rubros',
                'ordering': ['nivel', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nivel', 'nombre'), name='rubro_unico_por_nivel')],
            },
        ),
    ]
