# Generated by Django 5.2.15 on 2026-07-05 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'perfil de filtro',
                'verbose_name_plural': 'perfiles de filtro',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PalabraIntencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('requerida', 'Requerida (confianza alta)'), ('vetada', 'Vetada (descarte duro)')], max_length=15)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'palabra de intención',
                'verbose_name_plural': 'palabras de intención',
                'constraints': [models.UniqueConstraint(fields=('texto', 'tipo'), name='intencion_unica')],
            },
        ),
        migrations.CreateModel(
            name='ReglaKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('incluir', 'Inclusión'), ('excluir', 'Exclusión'), ('bypass', 'Bypass (rescate)'), ('exclusion_dura', 'Exclusión dura (no bypasseable)')], max_length=20)),
                ('campo', models.CharField(blank=True, choices=[('nombre', 'Nombre y descripción'), ('nivel1', 'Taxonomía Nivel 1'), ('nivel2', 'Taxonomía Nivel 2'), ('nivel3', 'Taxonomía Nivel 3'), ('generico', 'Genérico'), ('organismo', 'Organismo'), ('valor', 'Tipo de adquisición'), ('componente', 'Descripción del producto/servicio')], default='', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='perfiles.perfilfiltro')),
            ],
            options={
                'verbose_name': 'regla de keyword',
                'verbose_name_plural': 'reglas de keyword',
                'constraints': [models.UniqueConstraint(fields=('perfil', 'tipo', 'campo', 'texto'), name='regla_unica_por_perfil')],
            },
        ),
    ]
