# Generated by Django 5.2.15 on 2026-07-06 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilfiltro',
            options={'ordering': ['codigo'], 'verbose_name': 'búsqueda guardada', 'verbose_name_plural': 'búsquedas guardadas'},
        ),
        migrations.AddField(
            model_name='perfilfiltro',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busquedas', to=settings.AUTH_USER_MODEL),
        ),
    ]
